// Quick test script to debug NGO verification
// Run this with: dart test_ngo_debug.dart

import 'package:cloud_firestore/cloud_firestore.dart';

void main() async {
  print('🔍 NGO Debug Test Script');
  print('========================');
  
  // This script should help you understand what's in your database
  print('Step 1: Check if you have any NGOs created in the admin dashboard');
  print('Step 2: Use the exact NGO name and code from the admin dashboard');
  print('Step 3: Make sure NGO name and code are copied exactly (case-sensitive)');
  print('');
  print('Common Issues:');
  print('- NGO not created yet: Go to admin dashboard → Create NGO first');
  print('- Case sensitivity: "TestNGO" ≠ "testngo"');
  print('- Extra spaces: "Test NGO" ≠ "Test NGO "');
  print('- Wrong NGO code: Each NGO has a unique code generated by admin');
  print('');
  print('To fix:');
  print('1. Login as admin');
  print('2. Go to Admin Dashboard → NGOs tab');
  print('3. Create a new NGO if none exists');
  print('4. Note down the EXACT NGO name and code');
  print('5. Use those exact values in signup');
}
