// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8H4PT7zmcap-NHBNca8xDzS22wNNdQg',
    appId: '1:876605866101:web:5e7ec423c19d5f9a93b83c',
    messagingSenderId: '876605866101',
    projectId: 'ngo-app-4e7a9',
    authDomain: 'ngo-app-4e7a9.firebaseapp.com',
    storageBucket: 'ngo-app-4e7a9.firebasestorage.app',
    measurementId: 'G-W46N1ZQPBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFzbdrm6S6DBKrR9Wqk--e3xgKUEJhw0',
    appId: '1:876605866101:android:b4821894ea264a0393b83c',
    messagingSenderId: '876605866101',
    projectId: 'ngo-app-4e7a9',
    storageBucket: 'ngo-app-4e7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIjBi-z-6ID4G-tDJQaKMbZB0l_cDaqs',
    appId: '1:876605866101:ios:d109cf09a4d132ce93b83c',
    messagingSenderId: '876605866101',
    projectId: 'ngo-app-4e7a9',
    storageBucket: 'ngo-app-4e7a9.firebasestorage.app',
    iosBundleId: 'com.example.connectContribute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUIjBi-z-6ID4G-tDJQaKMbZB0l_cDaqs',
    appId: '1:876605866101:ios:d109cf09a4d132ce93b83c',
    messagingSenderId: '876605866101',
    projectId: 'ngo-app-4e7a9',
    storageBucket: 'ngo-app-4e7a9.firebasestorage.app',
    iosBundleId: 'com.example.connectContribute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8H4PT7zmcap-NHBNca8xDzS22wNNdQg',
    appId: '1:876605866101:web:5aed163826e8145193b83c',
    messagingSenderId: '876605866101',
    projectId: 'ngo-app-4e7a9',
    authDomain: 'ngo-app-4e7a9.firebaseapp.com',
    storageBucket: 'ngo-app-4e7a9.firebasestorage.app',
    measurementId: 'G-9H9BDM5WGQ',
  );
}
